from base_actions import *
from mixins import _KeyboardMixin

class KeyboardPress(_KeyboardMixin, Press): ...
class KeyboardRelease(_KeyboardMixin, Release): ...
class KeyboardHold(_KeyboardMixin, Hold): ...
class KeyboardTap(_KeyboardMixin, Tap): ...