from base_actions import *
from mixins import _KeyboardMixin

class KeyboardTap(_KeyboardMixin, Tap): ...
class KeyboardHold(_KeyboardMixin, Hold): ...
class KeyboardPress(_KeyboardMixin, Press): ...
class KeyboardRelease(_KeyboardMixin, Release): ...