from base_actions import *
from mixins import _MouseMixin

class MousePress(_MouseMixin, Press): ...
class MouseRelease(_MouseMixin, Release): ...
class MouseHold(_MouseMixin, Hold): ...
class MouseTap(_MouseMixin, Tap): ...