from base_actions import *
from mixins import *
from abstract import Action


class KeyboardTap(KeyboardMixin, Tap): ...
class MouseTap(MouseMixin, Tap): ...

class KeyboardHold(KeyboardMixin, Hold): ...
class MouseHold(MouseMixin, Hold): ...

class KeyboardPress(KeyboardMixin, Press): ...
class MousePress(MouseMixin, Press): ...

class KeyboardRelease(KeyboardMixin, Release): ...
class MouseRelease(MouseMixin, Release): ...


class Rest(Action):
    __slots__ = ['time']
    
    def __init__(self, time):
        self.time = time
    
    async def act(self):
        await asyncio.sleep(self.time)